### Update patient information
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "test UPDATED",
  "email": "test@email.com",
  "address": "123 main street",
  "dateOfBirth": "2005-03-28"
}
###